### ISSUE TITLE
The mysterious case of vanishing ideas

### ISSUE THREAD

**Issue by wammar** [higgood/idea-factory-users#1]
**Context**
Was it your first time using the tool? 100th time? 
I've used the tool a bunch of times before.

Were you alone? 
No, I was showing it to a potential client actually.

Were you tired and hungry? 
No, I was feeling good before this incident.

**Describe the bug**
We were brainstorming solutions for the homelessness problem in Seattle. I was reading out loud as she was putting away the dishes after dinner. We paused for a minute to discuss the efficacy of using solar power to heat homes in Seattle. A few minutes later, I wanted to read the next idea off the screen, but EVERYTHING was gone. I reran the tool but I got different output and it wasn't as good. How are we going to solve homelessness in Seattle now?!! It's all YOUR fault.

**[Required] Where did you encounter the bug**
[ ] While creating your account (first time user)
[ ] While logging in to your account
[ ] While applying changes to the settings (e.g., # of papers)
[ ] While typing the query
[ ] While Idea Factory was thinking or generating text
[ x ] After Idea Factory was done generating text

**[Required] Reality vs. Expectation**
As a "normal" person, I expected the generated text to STAY THERE. But it disappeared mysteriously! I thought maybe the text is still there but the color is off, but I wasn't able to "select" the text either.

**Screenshots**
![image](https://github.com/higgood/idea-factory-users/assets/1858803/2b260dbb-bee3-48e1-8005-68f1f8e2889b)

**Desktop (if applicable):**
 - OS: iOS v12.6.7
 - Browser: chrome v117.0.5938.92

**Comment by Mox301** [comment]
Solved :)
