### ISSUE TITLE
When the user requests to reset their password, don't question it!

### ISSUE THREAD

**Issue by wammar** [higgood/idea-factory-users#2]
**Is your feature request related to a problem? Please describe.**
When I tried to reset my password, put in my email address then clicked ENTER, I got a message that says "We're going to send a verification code after you click "Send". Of course, as a lazy-ass user, I didn't read the fine print, and I just went to my inbox, checked my spam folder, etc. without clicking Send. I ALREADY told Idea Factory that I want to reset my password, put in my email, and clicked a button. That's plenty of evidence I actually WANT TO reset. Please don't make me do any additional work. 

**Describe the solution you'd like**
Instead of the current behavior where the "Send" button must be clicked before the verificaiton code is sent to the user's email, please send the verification code right away, and give the user a message that asks them to look for it in their inbox/spam folder then click the same button but with a different label, something like "Got the verification code!" which sends the user to the next screen where they get to put in the new password twice. Please also tell the user what to do if they don't get the verification code, e.g., provide a link to this repo and invite them to create an issue.

**Describe alternatives you've considered**
We could keep it as it is, but I won't be able to share it with more people with pride because it's such an easy fix.

**Comment by Mox301** [comment]
Solved 👍
