### ISSUE TITLE
Design partners invitations are not coming through.

### ISSUE THREAD

**Issue by wammar** [higgood/idea-factory-users#5]
**Context**
I added temp@holistic-intelligence.net as a design partner in https://docs.google.com/spreadsheets/d/1dnFJGSvd8kxvf6g3GqrOVkOZo5vCWvquyajQ1a4CP9E/edit?usp=drivesdk
Then waited for 5 min as instructed. No email invitation was received. 15 min later, still no email and it is not in the spam folder either. (And yes I'm a little on edge this morning due to some network connectivity issues. 😅)

**Describe the bug**
The service which monitors the list of design partners and sends invites as needed is not working as expected, ie, not sending invites within 5 min of adding the record to the designated sheet.

**[Required] Where did you encounter the bug**
[X] While creating your account (first time user)

**[Required] Reality vs. Expectation**
Expectation: receive an email at temp@holi... before 10:50am PT.
Reality: no emails until 11:10am PT.

Thank you for improving the Idea Factory!!

**Comment by Mox301** [comment]
Solved
