### ISSUE TITLE
Design partner reports a glitch in our feedback form

### ISSUE THREAD

**Issue by wammar** [higgood/idea-factory-users#6]
**Context**
User was trying the tool for the second time and reported some feedback in text, then edited the query. Then was surprised to find that the text in the feedback form was not removed, even though the other fields were reset.

**Describe the bug**
When the user submits textual feedback, then clicks Think again, the text feedback is not removed. And it should be.

**[Required] Where did you encounter the bug**
[ ] While creating your account (first time user)
[ ] While logging in to your account
[ ] While applying changes to the settings (e.g., # of papers)
[ ] While typing the query
[ ] While Idea Factory was thinking or generating text
[x] After Idea Factory was done generating text

**[Required] Reality vs. Expectation**
Text field in feedback form should be empty.
It was not empty; It had the same text that was submitted.

**Comment by Mox301** [comment]
Solved :)
