### ISSUE TITLE
Description and typo

### ISSUE THREAD

**Issue by silviaprt** [higgood/idea-factory-users#9]
**Describe the bug**
1) Not very clear in the rating panel that this is about the Research questions
2) Typo in the selection, 'obvious' misspelled ad 'obivious'

**[Required] Where did you encounter the bug**
[x] When rating the research questions

**[Required] Reality vs. Expectation**
1) Suggest changing the rating panel heading from 'Feedback' to 'Feedback (Research questions)'
2) From 'slightly obivious' to 'slightly obvious'

**Comment by Mox301** [comment]
Thank you for your feedback, the typo is corrected :)
